import {
  Activity,
  BarChart3,
  Building2,
  CalendarClock,
  KeyRound,
  Settings2,
  Target,
  TrendingUp,
  Users,
} from "lucide-react";
import type { NavGroup, NavItem } from "./navigation.types";
import type { Role } from "./roles";

const CRM_ROLES: readonly Role[] = ["SALES_MANAGER"];

export const CRM_NAV_GROUPS: readonly NavGroup[] = [
  { id: "revenue", label: "Revenue", defaultOpen: true },
  { id: "work", label: "Work", defaultOpen: true },
  { id: "stakeholders", label: "Team", defaultOpen: true },
  { id: "account", label: "Account", defaultOpen: true },
];

export const CRM_NAV_ITEMS: readonly NavItem[] = [
  {
    workspace: "sales-crm",
    label: "Revenue Command",
    description: "Pipeline, forecast and today's priorities",
    icon: Target,
    route: "/sales-crm",
    group: "revenue",
    roles: CRM_ROLES,
    permission: "crm:read",
  },
  {
    workspace: "sales-crm",
    label: "Opportunities",
    description: "Board and table across every stage",
    icon: TrendingUp,
    route: "/sales-crm/opportunities",
    group: "revenue",
    roles: CRM_ROLES,
    permission: "crm:read",
    badge: { key: "crmOpenOpportunities", tone: "info" },
  },
  {
    workspace: "sales-crm",
    label: "Forecast",
    description: "Commit, best case and gap to target",
    icon: BarChart3,
    route: "/sales-crm/forecast",
    group: "revenue",
    roles: CRM_ROLES,
    permission: "crm:read",
  },
  {
    workspace: "sales-crm",
    label: "Follow-ups",
    description: "Overdue, today and upcoming next actions",
    icon: CalendarClock,
    route: "/sales-crm/follow-ups",
    group: "work",
    roles: CRM_ROLES,
    permission: "crm:read",
    badge: { key: "crmOverdueFollowUps", tone: "critical" },
  },
  {
    workspace: "sales-crm",
    label: "Activities",
    description: "Calls, emails, meetings and notes",
    icon: Activity,
    route: "/sales-crm/activities",
    group: "work",
    roles: CRM_ROLES,
    permission: "crm:read",
  },
  {
    workspace: "sales-crm",
    label: "Accounts",
    description: "Commercial view of every company",
    icon: Building2,
    route: "/sales-crm/accounts",
    group: "work",
    roles: CRM_ROLES,
    permission: "client:read",
  },
  {
    workspace: "sales-crm",
    label: "Sales Team",
    description: "Owner workload and win rates",
    icon: Users,
    route: "/sales-crm/team",
    group: "stakeholders",
    roles: CRM_ROLES,
    permission: "crm:write",
  },
  {
    workspace: "sales-crm",
    label: "CRM Settings",
    description: "Stages, sources and follow-up defaults",
    icon: Settings2,
    route: "/sales-crm/settings",
    group: "account",
    roles: CRM_ROLES,
    permission: "crm:read",
  },
  {
    workspace: "sales-crm",
    label: "Account Security",
    description: "Sessions and sign-in activity",
    icon: KeyRound,
    route: "/change-password",
    group: "account",
    roles: CRM_ROLES,
    permission: "crm:read",
  },
];
