export const PERMISSIONS = [
  "dashboard:read",
  "client:read",
  "client:write",
  "case:read",
  "case:create",
  "case:transition",
  "consent:manage",
  "document:read",
  "document:write",
  "task:read",
  "task:write",
  "clarification:read",
  "clarification:write",
  "qa:review",
  "report:read",
  "report:generate",
  "field-visit:read",
  "field-visit:write",
  "field-evidence:read",
  "audit:read",
  "settings:manage",
  "crm:read",
  "crm:write",
  "finance:read",
  "finance:write",
  "user:read",
  "user:write",
  "notification:read",
  "vendor:assign",
  "vendor:review",
  "support:read",
  "support:handle",
  "support:request",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const PERMISSION_LABELS: Record<Permission, string> = {
  "dashboard:read": "View operational dashboards",
  "client:read": "View client organisations",
  "client:write": "Create and update clients",
  "case:read": "View verification cases",
  "case:create": "Create verification cases",
  "case:transition": "Move cases through delivery stages",
  "consent:manage": "Request and manage candidate consent",
  "document:read": "View protected case documents",
  "document:write": "Upload and replace case documents",
  "task:read": "View verification assignments",
  "task:write": "Assign and execute verification tasks",
  "clarification:read": "View candidate and client clarifications",
  "clarification:write": "Raise, respond to and resolve clarifications",
  "qa:review": "Claim and decide independent QA reviews",
  "report:read": "View and download verification reports",
  "report:generate": "Generate approved verification reports",
  "field-visit:read": "View assigned field visits",
  "field-visit:write": "Capture and complete field visits",
  "field-evidence:read": "Review protected field evidence",
  "audit:read": "Read the immutable audit trail",
  "settings:manage": "Manage platform policy and catalogues",
  "crm:read": "View pipeline and commercial activity",
  "crm:write": "Manage opportunities and activities",
  "finance:read": "View invoices and receivables",
  "finance:write": "Issue invoices and record collections",
  "user:read": "View user IDs and role access",
  "user:write": "Create, suspend and reset user IDs",
  "vendor:assign": "Assign client documents to vendors",
  "vendor:review": "Approve or reject documents assigned as a vendor",
  "support:read": "View client and employee progress for support",
  "support:handle": "Work the support request inbox",
  "support:request": "Raise support requests",
  "notification:read": "Read workspace notifications",
};
