/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as FieldExecutiveRouteImport } from './routes/field-executive'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as QaReviewRouteImport } from './routes/qa-review'
import { Route as SalesCrmRouteImport } from './routes/sales-crm'
import { Route as SpocRmRouteImport } from './routes/spoc-rm'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as VerifierRouteImport } from './routes/verifier'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminClientPortalRouteImport } from './routes/admin.client-portal'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminExceptionsRouteImport } from './routes/admin.exceptions'
import { Route as AdminFieldRouteImport } from './routes/admin.field'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminPrivacyRouteImport } from './routes/admin.privacy'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerifierRouteImport } from './routes/admin.verifier'
import { Route as CandidateAccessIdRouteImport } from './routes/candidate.$accessId'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ClarificationClarificationIdRouteImport } from './routes/clarification.$clarificationId'
import { Route as ClientPortalIndexRouteImport } from './routes/client-portal.index'
import { Route as ClientPortalActionsRouteImport } from './routes/client-portal.actions'
import { Route as ClientPortalAnalyticsRouteImport } from './routes/client-portal.analytics'
import { Route as ClientPortalBillingRouteImport } from './routes/client-portal.billing'
import { Route as ClientPortalReportsRouteImport } from './routes/client-portal.reports'
import { Route as ClientPortalVerificationsRouteImport } from './routes/client-portal.verifications'
import { Route as ConsentConsentIdRouteImport } from './routes/consent.$consentId'
import { Route as FinanceBillingRouteImport } from './routes/finance_.billing'
import { Route as FinanceCollectionsRouteImport } from './routes/finance_.collections'
import { Route as FinanceCreditRouteImport } from './routes/finance_.credit'
import { Route as FinanceInvoicesRouteImport } from './routes/finance_.invoices'
import { Route as FinanceStatementsRouteImport } from './routes/finance_.statements'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as OperationsAssignmentsRouteImport } from './routes/operations.assignments'
import { Route as OperationsCasesRouteImport } from './routes/operations.cases'
import { Route as OperationsClarificationsRouteImport } from './routes/operations.clarifications'
import { Route as OperationsExceptionsRouteImport } from './routes/operations.exceptions'
import { Route as OperationsFieldRouteImport } from './routes/operations.field'
import { Route as OperationsSlaRouteImport } from './routes/operations.sla'
import { Route as OperationsTeamRouteImport } from './routes/operations.team'
import { Route as QaReviewCorrectionsRouteImport } from './routes/qa-review_.corrections'
import { Route as QaReviewHistoryRouteImport } from './routes/qa-review_.history'
import { Route as QaReviewMineRouteImport } from './routes/qa-review_.mine'
import { Route as QaReviewOverviewRouteImport } from './routes/qa-review_.overview'
import { Route as SalesCrmIndexRouteImport } from './routes/sales-crm.index'
import { Route as SalesCrmAccountsRouteImport } from './routes/sales-crm.accounts'
import { Route as SalesCrmActivitiesRouteImport } from './routes/sales-crm.activities'
import { Route as SalesCrmFollowUpsRouteImport } from './routes/sales-crm.follow-ups'
import { Route as SalesCrmForecastRouteImport } from './routes/sales-crm.forecast'
import { Route as SalesCrmOpportunitiesRouteImport } from './routes/sales-crm.opportunities'
import { Route as SalesCrmSettingsRouteImport } from './routes/sales-crm.settings'
import { Route as SalesCrmTeamRouteImport } from './routes/sales-crm.team'
import { Route as SpocRmIndexRouteImport } from './routes/spoc-rm.index'
import { Route as SpocRmClientsRouteImport } from './routes/spoc-rm.clients'
import { Route as SpocRmRecordsRouteImport } from './routes/spoc-rm.records'
import { Route as SpocRmVendorsRouteImport } from './routes/spoc-rm.vendors'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportEmployeesRouteImport } from './routes/support.employees'
import { Route as SupportRequestsRouteImport } from './routes/support.requests'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorAllRouteImport } from './routes/vendor.all'
import { Route as VendorApprovedRouteImport } from './routes/vendor.approved'
import { Route as VendorLogsRouteImport } from './routes/vendor.logs'
import { Route as VendorPendingRouteImport } from './routes/vendor.pending'
import { Route as VendorRejectedRouteImport } from './routes/vendor.rejected'
import { Route as VendorTeamRouteImport } from './routes/vendor.team'
import { Route as VerifierIndexRouteImport } from './routes/verifier.index'
import { Route as VerifierBlockersRouteImport } from './routes/verifier.blockers'
import { Route as VerifierHistoryRouteImport } from './routes/verifier.history'
import { Route as VerifierPerformanceRouteImport } from './routes/verifier.performance'
import { Route as VerifierQueueRouteImport } from './routes/verifier.queue'
import { Route as VerifierSlaRouteImport } from './routes/verifier.sla'
import { Route as ReportsVerifyAuthenticityCodeRouteImport } from './routes/reports.verify.$authenticityCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldExecutiveRoute = FieldExecutiveRouteImport.update({
  id: '/field-executive',
  path: '/field-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const QaReviewRoute = QaReviewRouteImport.update({
  id: '/qa-review',
  path: '/qa-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCrmRoute = SalesCrmRouteImport.update({
  id: '/sales-crm',
  path: '/sales-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SpocRmRoute = SpocRmRouteImport.update({
  id: '/spoc-rm',
  path: '/spoc-rm',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierRoute = VerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientPortalRoute = AdminClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExceptionsRoute = AdminExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFieldRoute = AdminFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrivacyRoute = AdminPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerifierRoute = AdminVerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => AdminRoute,
} as any)
const CandidateAccessIdRoute = CandidateAccessIdRouteImport.update({
  id: '/candidate/$accessId',
  path: '/candidate/$accessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarificationClarificationIdRoute =
  ClarificationClarificationIdRouteImport.update({
    id: '/clarification/$clarificationId',
    path: '/clarification/$clarificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientPortalIndexRoute = ClientPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientPortalRoute,
} as any)
const ClientPortalActionsRoute = ClientPortalActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ClientPortalRoute,
} as any)
const ClientPortalAnalyticsRoute = ClientPortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ClientPortalRoute,
} as any)
const ClientPortalBillingRoute = ClientPortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ClientPortalRoute,
} as any)
const ClientPortalReportsRoute = ClientPortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ClientPortalRoute,
} as any)
const ClientPortalVerificationsRoute =
  ClientPortalVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => ClientPortalRoute,
  } as any)
const ConsentConsentIdRoute = ConsentConsentIdRouteImport.update({
  id: '/consent/$consentId',
  path: '/consent/$consentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBillingRoute = FinanceBillingRouteImport.update({
  id: '/finance_/billing',
  path: '/finance/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCollectionsRoute = FinanceCollectionsRouteImport.update({
  id: '/finance_/collections',
  path: '/finance/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCreditRoute = FinanceCreditRouteImport.update({
  id: '/finance_/credit',
  path: '/finance/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/finance_/invoices',
  path: '/finance/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceStatementsRoute = FinanceStatementsRouteImport.update({
  id: '/finance_/statements',
  path: '/finance/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsAssignmentsRoute = OperationsAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsCasesRoute = OperationsCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsClarificationsRoute =
  OperationsClarificationsRouteImport.update({
    id: '/clarifications',
    path: '/clarifications',
    getParentRoute: () => OperationsRoute,
  } as any)
const OperationsExceptionsRoute = OperationsExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsFieldRoute = OperationsFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsSlaRoute = OperationsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsTeamRoute = OperationsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OperationsRoute,
} as any)
const QaReviewCorrectionsRoute = QaReviewCorrectionsRouteImport.update({
  id: '/qa-review_/corrections',
  path: '/qa-review/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const QaReviewHistoryRoute = QaReviewHistoryRouteImport.update({
  id: '/qa-review_/history',
  path: '/qa-review/history',
  getParentRoute: () => rootRouteImport,
} as any)
const QaReviewMineRoute = QaReviewMineRouteImport.update({
  id: '/qa-review_/mine',
  path: '/qa-review/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const QaReviewOverviewRoute = QaReviewOverviewRouteImport.update({
  id: '/qa-review_/overview',
  path: '/qa-review/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCrmIndexRoute = SalesCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmAccountsRoute = SalesCrmAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmActivitiesRoute = SalesCrmActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmFollowUpsRoute = SalesCrmFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmForecastRoute = SalesCrmForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmOpportunitiesRoute = SalesCrmOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmSettingsRoute = SalesCrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SalesCrmTeamRoute = SalesCrmTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SalesCrmRoute,
} as any)
const SpocRmIndexRoute = SpocRmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpocRmRoute,
} as any)
const SpocRmClientsRoute = SpocRmClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => SpocRmRoute,
} as any)
const SpocRmRecordsRoute = SpocRmRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => SpocRmRoute,
} as any)
const SpocRmVendorsRoute = SpocRmVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => SpocRmRoute,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SupportEmployeesRoute = SupportEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => SupportRoute,
} as any)
const SupportRequestsRoute = SupportRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => SupportRoute,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAllRoute = VendorAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => VendorRoute,
} as any)
const VendorApprovedRoute = VendorApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => VendorRoute,
} as any)
const VendorLogsRoute = VendorLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPendingRoute = VendorPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => VendorRoute,
} as any)
const VendorRejectedRoute = VendorRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => VendorRoute,
} as any)
const VendorTeamRoute = VendorTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => VendorRoute,
} as any)
const VerifierIndexRoute = VerifierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierBlockersRoute = VerifierBlockersRouteImport.update({
  id: '/blockers',
  path: '/blockers',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierHistoryRoute = VerifierHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierPerformanceRoute = VerifierPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierQueueRoute = VerifierQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierSlaRoute = VerifierSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => VerifierRoute,
} as any)
const ReportsVerifyAuthenticityCodeRoute =
  ReportsVerifyAuthenticityCodeRouteImport.update({
    id: '/reports/verify/$authenticityCode',
    path: '/reports/verify/$authenticityCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/client-portal': typeof ClientPortalRouteWithChildren
  '/field-executive': typeof FieldExecutiveRoute
  '/finance': typeof FinanceRoute
  '/operations': typeof OperationsRouteWithChildren
  '/qa-review': typeof QaReviewRoute
  '/sales-crm': typeof SalesCrmRouteWithChildren
  '/spoc-rm': typeof SpocRmRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/verifier': typeof VerifierRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/client-portal': typeof AdminClientPortalRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/field': typeof AdminFieldRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifier': typeof AdminVerifierRoute
  '/candidate/$accessId': typeof CandidateAccessIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clarification/$clarificationId': typeof ClarificationClarificationIdRoute
  '/client-portal/actions': typeof ClientPortalActionsRoute
  '/client-portal/analytics': typeof ClientPortalAnalyticsRoute
  '/client-portal/billing': typeof ClientPortalBillingRoute
  '/client-portal/reports': typeof ClientPortalReportsRoute
  '/client-portal/verifications': typeof ClientPortalVerificationsRoute
  '/consent/$consentId': typeof ConsentConsentIdRoute
  '/finance/billing': typeof FinanceBillingRoute
  '/finance/collections': typeof FinanceCollectionsRoute
  '/finance/credit': typeof FinanceCreditRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/operations/assignments': typeof OperationsAssignmentsRoute
  '/operations/cases': typeof OperationsCasesRoute
  '/operations/clarifications': typeof OperationsClarificationsRoute
  '/operations/exceptions': typeof OperationsExceptionsRoute
  '/operations/field': typeof OperationsFieldRoute
  '/operations/sla': typeof OperationsSlaRoute
  '/operations/team': typeof OperationsTeamRoute
  '/qa-review/corrections': typeof QaReviewCorrectionsRoute
  '/qa-review/history': typeof QaReviewHistoryRoute
  '/qa-review/mine': typeof QaReviewMineRoute
  '/qa-review/overview': typeof QaReviewOverviewRoute
  '/sales-crm/accounts': typeof SalesCrmAccountsRoute
  '/sales-crm/activities': typeof SalesCrmActivitiesRoute
  '/sales-crm/follow-ups': typeof SalesCrmFollowUpsRoute
  '/sales-crm/forecast': typeof SalesCrmForecastRoute
  '/sales-crm/opportunities': typeof SalesCrmOpportunitiesRoute
  '/sales-crm/settings': typeof SalesCrmSettingsRoute
  '/sales-crm/team': typeof SalesCrmTeamRoute
  '/spoc-rm/clients': typeof SpocRmClientsRoute
  '/spoc-rm/records': typeof SpocRmRecordsRoute
  '/spoc-rm/vendors': typeof SpocRmVendorsRoute
  '/support/employees': typeof SupportEmployeesRoute
  '/support/requests': typeof SupportRequestsRoute
  '/vendor/all': typeof VendorAllRoute
  '/vendor/approved': typeof VendorApprovedRoute
  '/vendor/logs': typeof VendorLogsRoute
  '/vendor/pending': typeof VendorPendingRoute
  '/vendor/rejected': typeof VendorRejectedRoute
  '/vendor/team': typeof VendorTeamRoute
  '/verifier/blockers': typeof VerifierBlockersRoute
  '/verifier/history': typeof VerifierHistoryRoute
  '/verifier/performance': typeof VerifierPerformanceRoute
  '/verifier/queue': typeof VerifierQueueRoute
  '/verifier/sla': typeof VerifierSlaRoute
  '/admin/': typeof AdminIndexRoute
  '/client-portal/': typeof ClientPortalIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/sales-crm/': typeof SalesCrmIndexRoute
  '/spoc-rm/': typeof SpocRmIndexRoute
  '/support/': typeof SupportIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/verifier/': typeof VerifierIndexRoute
  '/reports/verify/$authenticityCode': typeof ReportsVerifyAuthenticityCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/field-executive': typeof FieldExecutiveRoute
  '/finance': typeof FinanceRoute
  '/qa-review': typeof QaReviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/client-portal': typeof AdminClientPortalRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/field': typeof AdminFieldRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifier': typeof AdminVerifierRoute
  '/candidate/$accessId': typeof CandidateAccessIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clarification/$clarificationId': typeof ClarificationClarificationIdRoute
  '/client-portal/actions': typeof ClientPortalActionsRoute
  '/client-portal/analytics': typeof ClientPortalAnalyticsRoute
  '/client-portal/billing': typeof ClientPortalBillingRoute
  '/client-portal/reports': typeof ClientPortalReportsRoute
  '/client-portal/verifications': typeof ClientPortalVerificationsRoute
  '/consent/$consentId': typeof ConsentConsentIdRoute
  '/finance/billing': typeof FinanceBillingRoute
  '/finance/collections': typeof FinanceCollectionsRoute
  '/finance/credit': typeof FinanceCreditRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/operations/assignments': typeof OperationsAssignmentsRoute
  '/operations/cases': typeof OperationsCasesRoute
  '/operations/clarifications': typeof OperationsClarificationsRoute
  '/operations/exceptions': typeof OperationsExceptionsRoute
  '/operations/field': typeof OperationsFieldRoute
  '/operations/sla': typeof OperationsSlaRoute
  '/operations/team': typeof OperationsTeamRoute
  '/qa-review/corrections': typeof QaReviewCorrectionsRoute
  '/qa-review/history': typeof QaReviewHistoryRoute
  '/qa-review/mine': typeof QaReviewMineRoute
  '/qa-review/overview': typeof QaReviewOverviewRoute
  '/sales-crm/accounts': typeof SalesCrmAccountsRoute
  '/sales-crm/activities': typeof SalesCrmActivitiesRoute
  '/sales-crm/follow-ups': typeof SalesCrmFollowUpsRoute
  '/sales-crm/forecast': typeof SalesCrmForecastRoute
  '/sales-crm/opportunities': typeof SalesCrmOpportunitiesRoute
  '/sales-crm/settings': typeof SalesCrmSettingsRoute
  '/sales-crm/team': typeof SalesCrmTeamRoute
  '/spoc-rm/clients': typeof SpocRmClientsRoute
  '/spoc-rm/records': typeof SpocRmRecordsRoute
  '/spoc-rm/vendors': typeof SpocRmVendorsRoute
  '/support/employees': typeof SupportEmployeesRoute
  '/support/requests': typeof SupportRequestsRoute
  '/vendor/all': typeof VendorAllRoute
  '/vendor/approved': typeof VendorApprovedRoute
  '/vendor/logs': typeof VendorLogsRoute
  '/vendor/pending': typeof VendorPendingRoute
  '/vendor/rejected': typeof VendorRejectedRoute
  '/vendor/team': typeof VendorTeamRoute
  '/verifier/blockers': typeof VerifierBlockersRoute
  '/verifier/history': typeof VerifierHistoryRoute
  '/verifier/performance': typeof VerifierPerformanceRoute
  '/verifier/queue': typeof VerifierQueueRoute
  '/verifier/sla': typeof VerifierSlaRoute
  '/admin': typeof AdminIndexRoute
  '/client-portal': typeof ClientPortalIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/sales-crm': typeof SalesCrmIndexRoute
  '/spoc-rm': typeof SpocRmIndexRoute
  '/support': typeof SupportIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/verifier': typeof VerifierIndexRoute
  '/reports/verify/$authenticityCode': typeof ReportsVerifyAuthenticityCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/client-portal': typeof ClientPortalRouteWithChildren
  '/field-executive': typeof FieldExecutiveRoute
  '/finance': typeof FinanceRoute
  '/operations': typeof OperationsRouteWithChildren
  '/qa-review': typeof QaReviewRoute
  '/sales-crm': typeof SalesCrmRouteWithChildren
  '/spoc-rm': typeof SpocRmRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/verifier': typeof VerifierRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/client-portal': typeof AdminClientPortalRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/field': typeof AdminFieldRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifier': typeof AdminVerifierRoute
  '/candidate/$accessId': typeof CandidateAccessIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clarification/$clarificationId': typeof ClarificationClarificationIdRoute
  '/client-portal/actions': typeof ClientPortalActionsRoute
  '/client-portal/analytics': typeof ClientPortalAnalyticsRoute
  '/client-portal/billing': typeof ClientPortalBillingRoute
  '/client-portal/reports': typeof ClientPortalReportsRoute
  '/client-portal/verifications': typeof ClientPortalVerificationsRoute
  '/consent/$consentId': typeof ConsentConsentIdRoute
  '/finance_/billing': typeof FinanceBillingRoute
  '/finance_/collections': typeof FinanceCollectionsRoute
  '/finance_/credit': typeof FinanceCreditRoute
  '/finance_/invoices': typeof FinanceInvoicesRoute
  '/finance_/statements': typeof FinanceStatementsRoute
  '/operations/assignments': typeof OperationsAssignmentsRoute
  '/operations/cases': typeof OperationsCasesRoute
  '/operations/clarifications': typeof OperationsClarificationsRoute
  '/operations/exceptions': typeof OperationsExceptionsRoute
  '/operations/field': typeof OperationsFieldRoute
  '/operations/sla': typeof OperationsSlaRoute
  '/operations/team': typeof OperationsTeamRoute
  '/qa-review_/corrections': typeof QaReviewCorrectionsRoute
  '/qa-review_/history': typeof QaReviewHistoryRoute
  '/qa-review_/mine': typeof QaReviewMineRoute
  '/qa-review_/overview': typeof QaReviewOverviewRoute
  '/sales-crm/accounts': typeof SalesCrmAccountsRoute
  '/sales-crm/activities': typeof SalesCrmActivitiesRoute
  '/sales-crm/follow-ups': typeof SalesCrmFollowUpsRoute
  '/sales-crm/forecast': typeof SalesCrmForecastRoute
  '/sales-crm/opportunities': typeof SalesCrmOpportunitiesRoute
  '/sales-crm/settings': typeof SalesCrmSettingsRoute
  '/sales-crm/team': typeof SalesCrmTeamRoute
  '/spoc-rm/clients': typeof SpocRmClientsRoute
  '/spoc-rm/records': typeof SpocRmRecordsRoute
  '/spoc-rm/vendors': typeof SpocRmVendorsRoute
  '/support/employees': typeof SupportEmployeesRoute
  '/support/requests': typeof SupportRequestsRoute
  '/vendor/all': typeof VendorAllRoute
  '/vendor/approved': typeof VendorApprovedRoute
  '/vendor/logs': typeof VendorLogsRoute
  '/vendor/pending': typeof VendorPendingRoute
  '/vendor/rejected': typeof VendorRejectedRoute
  '/vendor/team': typeof VendorTeamRoute
  '/verifier/blockers': typeof VerifierBlockersRoute
  '/verifier/history': typeof VerifierHistoryRoute
  '/verifier/performance': typeof VerifierPerformanceRoute
  '/verifier/queue': typeof VerifierQueueRoute
  '/verifier/sla': typeof VerifierSlaRoute
  '/admin/': typeof AdminIndexRoute
  '/client-portal/': typeof ClientPortalIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/sales-crm/': typeof SalesCrmIndexRoute
  '/spoc-rm/': typeof SpocRmIndexRoute
  '/support/': typeof SupportIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/verifier/': typeof VerifierIndexRoute
  '/reports/verify/$authenticityCode': typeof ReportsVerifyAuthenticityCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/client-portal'
    | '/field-executive'
    | '/finance'
    | '/operations'
    | '/qa-review'
    | '/sales-crm'
    | '/spoc-rm'
    | '/support'
    | '/vendor'
    | '/verifier'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/client-portal'
    | '/admin/clients'
    | '/admin/exceptions'
    | '/admin/field'
    | '/admin/finance'
    | '/admin/privacy'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifier'
    | '/candidate/$accessId'
    | '/cases/$caseId'
    | '/clarification/$clarificationId'
    | '/client-portal/actions'
    | '/client-portal/analytics'
    | '/client-portal/billing'
    | '/client-portal/reports'
    | '/client-portal/verifications'
    | '/consent/$consentId'
    | '/finance/billing'
    | '/finance/collections'
    | '/finance/credit'
    | '/finance/invoices'
    | '/finance/statements'
    | '/operations/assignments'
    | '/operations/cases'
    | '/operations/clarifications'
    | '/operations/exceptions'
    | '/operations/field'
    | '/operations/sla'
    | '/operations/team'
    | '/qa-review/corrections'
    | '/qa-review/history'
    | '/qa-review/mine'
    | '/qa-review/overview'
    | '/sales-crm/accounts'
    | '/sales-crm/activities'
    | '/sales-crm/follow-ups'
    | '/sales-crm/forecast'
    | '/sales-crm/opportunities'
    | '/sales-crm/settings'
    | '/sales-crm/team'
    | '/spoc-rm/clients'
    | '/spoc-rm/records'
    | '/spoc-rm/vendors'
    | '/support/employees'
    | '/support/requests'
    | '/vendor/all'
    | '/vendor/approved'
    | '/vendor/logs'
    | '/vendor/pending'
    | '/vendor/rejected'
    | '/vendor/team'
    | '/verifier/blockers'
    | '/verifier/history'
    | '/verifier/performance'
    | '/verifier/queue'
    | '/verifier/sla'
    | '/admin/'
    | '/client-portal/'
    | '/operations/'
    | '/sales-crm/'
    | '/spoc-rm/'
    | '/support/'
    | '/vendor/'
    | '/verifier/'
    | '/reports/verify/$authenticityCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/field-executive'
    | '/finance'
    | '/qa-review'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/client-portal'
    | '/admin/clients'
    | '/admin/exceptions'
    | '/admin/field'
    | '/admin/finance'
    | '/admin/privacy'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifier'
    | '/candidate/$accessId'
    | '/cases/$caseId'
    | '/clarification/$clarificationId'
    | '/client-portal/actions'
    | '/client-portal/analytics'
    | '/client-portal/billing'
    | '/client-portal/reports'
    | '/client-portal/verifications'
    | '/consent/$consentId'
    | '/finance/billing'
    | '/finance/collections'
    | '/finance/credit'
    | '/finance/invoices'
    | '/finance/statements'
    | '/operations/assignments'
    | '/operations/cases'
    | '/operations/clarifications'
    | '/operations/exceptions'
    | '/operations/field'
    | '/operations/sla'
    | '/operations/team'
    | '/qa-review/corrections'
    | '/qa-review/history'
    | '/qa-review/mine'
    | '/qa-review/overview'
    | '/sales-crm/accounts'
    | '/sales-crm/activities'
    | '/sales-crm/follow-ups'
    | '/sales-crm/forecast'
    | '/sales-crm/opportunities'
    | '/sales-crm/settings'
    | '/sales-crm/team'
    | '/spoc-rm/clients'
    | '/spoc-rm/records'
    | '/spoc-rm/vendors'
    | '/support/employees'
    | '/support/requests'
    | '/vendor/all'
    | '/vendor/approved'
    | '/vendor/logs'
    | '/vendor/pending'
    | '/vendor/rejected'
    | '/vendor/team'
    | '/verifier/blockers'
    | '/verifier/history'
    | '/verifier/performance'
    | '/verifier/queue'
    | '/verifier/sla'
    | '/admin'
    | '/client-portal'
    | '/operations'
    | '/sales-crm'
    | '/spoc-rm'
    | '/support'
    | '/vendor'
    | '/verifier'
    | '/reports/verify/$authenticityCode'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/client-portal'
    | '/field-executive'
    | '/finance'
    | '/operations'
    | '/qa-review'
    | '/sales-crm'
    | '/spoc-rm'
    | '/support'
    | '/vendor'
    | '/verifier'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/client-portal'
    | '/admin/clients'
    | '/admin/exceptions'
    | '/admin/field'
    | '/admin/finance'
    | '/admin/privacy'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifier'
    | '/candidate/$accessId'
    | '/cases/$caseId'
    | '/clarification/$clarificationId'
    | '/client-portal/actions'
    | '/client-portal/analytics'
    | '/client-portal/billing'
    | '/client-portal/reports'
    | '/client-portal/verifications'
    | '/consent/$consentId'
    | '/finance_/billing'
    | '/finance_/collections'
    | '/finance_/credit'
    | '/finance_/invoices'
    | '/finance_/statements'
    | '/operations/assignments'
    | '/operations/cases'
    | '/operations/clarifications'
    | '/operations/exceptions'
    | '/operations/field'
    | '/operations/sla'
    | '/operations/team'
    | '/qa-review_/corrections'
    | '/qa-review_/history'
    | '/qa-review_/mine'
    | '/qa-review_/overview'
    | '/sales-crm/accounts'
    | '/sales-crm/activities'
    | '/sales-crm/follow-ups'
    | '/sales-crm/forecast'
    | '/sales-crm/opportunities'
    | '/sales-crm/settings'
    | '/sales-crm/team'
    | '/spoc-rm/clients'
    | '/spoc-rm/records'
    | '/spoc-rm/vendors'
    | '/support/employees'
    | '/support/requests'
    | '/vendor/all'
    | '/vendor/approved'
    | '/vendor/logs'
    | '/vendor/pending'
    | '/vendor/rejected'
    | '/vendor/team'
    | '/verifier/blockers'
    | '/verifier/history'
    | '/verifier/performance'
    | '/verifier/queue'
    | '/verifier/sla'
    | '/admin/'
    | '/client-portal/'
    | '/operations/'
    | '/sales-crm/'
    | '/spoc-rm/'
    | '/support/'
    | '/vendor/'
    | '/verifier/'
    | '/reports/verify/$authenticityCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ClientPortalRoute: typeof ClientPortalRouteWithChildren
  FieldExecutiveRoute: typeof FieldExecutiveRoute
  FinanceRoute: typeof FinanceRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  QaReviewRoute: typeof QaReviewRoute
  SalesCrmRoute: typeof SalesCrmRouteWithChildren
  SpocRmRoute: typeof SpocRmRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  VerifierRoute: typeof VerifierRouteWithChildren
  CandidateAccessIdRoute: typeof CandidateAccessIdRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ClarificationClarificationIdRoute: typeof ClarificationClarificationIdRoute
  ConsentConsentIdRoute: typeof ConsentConsentIdRoute
  FinanceBillingRoute: typeof FinanceBillingRoute
  FinanceCollectionsRoute: typeof FinanceCollectionsRoute
  FinanceCreditRoute: typeof FinanceCreditRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinanceStatementsRoute: typeof FinanceStatementsRoute
  QaReviewCorrectionsRoute: typeof QaReviewCorrectionsRoute
  QaReviewHistoryRoute: typeof QaReviewHistoryRoute
  QaReviewMineRoute: typeof QaReviewMineRoute
  QaReviewOverviewRoute: typeof QaReviewOverviewRoute
  ReportsVerifyAuthenticityCodeRoute: typeof ReportsVerifyAuthenticityCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-executive': {
      id: '/field-executive'
      path: '/field-executive'
      fullPath: '/field-executive'
      preLoaderRoute: typeof FieldExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-review': {
      id: '/qa-review'
      path: '/qa-review'
      fullPath: '/qa-review'
      preLoaderRoute: typeof QaReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-crm': {
      id: '/sales-crm'
      path: '/sales-crm'
      fullPath: '/sales-crm'
      preLoaderRoute: typeof SalesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoc-rm': {
      id: '/spoc-rm'
      path: '/spoc-rm'
      fullPath: '/spoc-rm'
      preLoaderRoute: typeof SpocRmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier': {
      id: '/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof VerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/client-portal': {
      id: '/admin/client-portal'
      path: '/client-portal'
      fullPath: '/admin/client-portal'
      preLoaderRoute: typeof AdminClientPortalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exceptions': {
      id: '/admin/exceptions'
      path: '/exceptions'
      fullPath: '/admin/exceptions'
      preLoaderRoute: typeof AdminExceptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/field': {
      id: '/admin/field'
      path: '/field'
      fullPath: '/admin/field'
      preLoaderRoute: typeof AdminFieldRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/privacy': {
      id: '/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AdminPrivacyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verifier': {
      id: '/admin/verifier'
      path: '/verifier'
      fullPath: '/admin/verifier'
      preLoaderRoute: typeof AdminVerifierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/candidate/$accessId': {
      id: '/candidate/$accessId'
      path: '/candidate/$accessId'
      fullPath: '/candidate/$accessId'
      preLoaderRoute: typeof CandidateAccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarification/$clarificationId': {
      id: '/clarification/$clarificationId'
      path: '/clarification/$clarificationId'
      fullPath: '/clarification/$clarificationId'
      preLoaderRoute: typeof ClarificationClarificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal/': {
      id: '/client-portal/'
      path: '/'
      fullPath: '/client-portal/'
      preLoaderRoute: typeof ClientPortalIndexRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/client-portal/actions': {
      id: '/client-portal/actions'
      path: '/actions'
      fullPath: '/client-portal/actions'
      preLoaderRoute: typeof ClientPortalActionsRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/client-portal/analytics': {
      id: '/client-portal/analytics'
      path: '/analytics'
      fullPath: '/client-portal/analytics'
      preLoaderRoute: typeof ClientPortalAnalyticsRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/client-portal/billing': {
      id: '/client-portal/billing'
      path: '/billing'
      fullPath: '/client-portal/billing'
      preLoaderRoute: typeof ClientPortalBillingRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/client-portal/reports': {
      id: '/client-portal/reports'
      path: '/reports'
      fullPath: '/client-portal/reports'
      preLoaderRoute: typeof ClientPortalReportsRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/client-portal/verifications': {
      id: '/client-portal/verifications'
      path: '/verifications'
      fullPath: '/client-portal/verifications'
      preLoaderRoute: typeof ClientPortalVerificationsRouteImport
      parentRoute: typeof ClientPortalRoute
    }
    '/consent/$consentId': {
      id: '/consent/$consentId'
      path: '/consent/$consentId'
      fullPath: '/consent/$consentId'
      preLoaderRoute: typeof ConsentConsentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/billing': {
      id: '/finance_/billing'
      path: '/finance/billing'
      fullPath: '/finance/billing'
      preLoaderRoute: typeof FinanceBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/collections': {
      id: '/finance_/collections'
      path: '/finance/collections'
      fullPath: '/finance/collections'
      preLoaderRoute: typeof FinanceCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/credit': {
      id: '/finance_/credit'
      path: '/finance/credit'
      fullPath: '/finance/credit'
      preLoaderRoute: typeof FinanceCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/invoices': {
      id: '/finance_/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance_/statements': {
      id: '/finance_/statements'
      path: '/finance/statements'
      fullPath: '/finance/statements'
      preLoaderRoute: typeof FinanceStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/assignments': {
      id: '/operations/assignments'
      path: '/assignments'
      fullPath: '/operations/assignments'
      preLoaderRoute: typeof OperationsAssignmentsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/cases': {
      id: '/operations/cases'
      path: '/cases'
      fullPath: '/operations/cases'
      preLoaderRoute: typeof OperationsCasesRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/clarifications': {
      id: '/operations/clarifications'
      path: '/clarifications'
      fullPath: '/operations/clarifications'
      preLoaderRoute: typeof OperationsClarificationsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/exceptions': {
      id: '/operations/exceptions'
      path: '/exceptions'
      fullPath: '/operations/exceptions'
      preLoaderRoute: typeof OperationsExceptionsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/field': {
      id: '/operations/field'
      path: '/field'
      fullPath: '/operations/field'
      preLoaderRoute: typeof OperationsFieldRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/sla': {
      id: '/operations/sla'
      path: '/sla'
      fullPath: '/operations/sla'
      preLoaderRoute: typeof OperationsSlaRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/team': {
      id: '/operations/team'
      path: '/team'
      fullPath: '/operations/team'
      preLoaderRoute: typeof OperationsTeamRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/qa-review_/corrections': {
      id: '/qa-review_/corrections'
      path: '/qa-review/corrections'
      fullPath: '/qa-review/corrections'
      preLoaderRoute: typeof QaReviewCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-review_/history': {
      id: '/qa-review_/history'
      path: '/qa-review/history'
      fullPath: '/qa-review/history'
      preLoaderRoute: typeof QaReviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-review_/mine': {
      id: '/qa-review_/mine'
      path: '/qa-review/mine'
      fullPath: '/qa-review/mine'
      preLoaderRoute: typeof QaReviewMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-review_/overview': {
      id: '/qa-review_/overview'
      path: '/qa-review/overview'
      fullPath: '/qa-review/overview'
      preLoaderRoute: typeof QaReviewOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-crm/': {
      id: '/sales-crm/'
      path: '/'
      fullPath: '/sales-crm/'
      preLoaderRoute: typeof SalesCrmIndexRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/accounts': {
      id: '/sales-crm/accounts'
      path: '/accounts'
      fullPath: '/sales-crm/accounts'
      preLoaderRoute: typeof SalesCrmAccountsRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/activities': {
      id: '/sales-crm/activities'
      path: '/activities'
      fullPath: '/sales-crm/activities'
      preLoaderRoute: typeof SalesCrmActivitiesRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/follow-ups': {
      id: '/sales-crm/follow-ups'
      path: '/follow-ups'
      fullPath: '/sales-crm/follow-ups'
      preLoaderRoute: typeof SalesCrmFollowUpsRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/forecast': {
      id: '/sales-crm/forecast'
      path: '/forecast'
      fullPath: '/sales-crm/forecast'
      preLoaderRoute: typeof SalesCrmForecastRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/opportunities': {
      id: '/sales-crm/opportunities'
      path: '/opportunities'
      fullPath: '/sales-crm/opportunities'
      preLoaderRoute: typeof SalesCrmOpportunitiesRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/settings': {
      id: '/sales-crm/settings'
      path: '/settings'
      fullPath: '/sales-crm/settings'
      preLoaderRoute: typeof SalesCrmSettingsRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/sales-crm/team': {
      id: '/sales-crm/team'
      path: '/team'
      fullPath: '/sales-crm/team'
      preLoaderRoute: typeof SalesCrmTeamRouteImport
      parentRoute: typeof SalesCrmRoute
    }
    '/spoc-rm/': {
      id: '/spoc-rm/'
      path: '/'
      fullPath: '/spoc-rm/'
      preLoaderRoute: typeof SpocRmIndexRouteImport
      parentRoute: typeof SpocRmRoute
    }
    '/spoc-rm/clients': {
      id: '/spoc-rm/clients'
      path: '/clients'
      fullPath: '/spoc-rm/clients'
      preLoaderRoute: typeof SpocRmClientsRouteImport
      parentRoute: typeof SpocRmRoute
    }
    '/spoc-rm/records': {
      id: '/spoc-rm/records'
      path: '/records'
      fullPath: '/spoc-rm/records'
      preLoaderRoute: typeof SpocRmRecordsRouteImport
      parentRoute: typeof SpocRmRoute
    }
    '/spoc-rm/vendors': {
      id: '/spoc-rm/vendors'
      path: '/vendors'
      fullPath: '/spoc-rm/vendors'
      preLoaderRoute: typeof SpocRmVendorsRouteImport
      parentRoute: typeof SpocRmRoute
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/employees': {
      id: '/support/employees'
      path: '/employees'
      fullPath: '/support/employees'
      preLoaderRoute: typeof SupportEmployeesRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/requests': {
      id: '/support/requests'
      path: '/requests'
      fullPath: '/support/requests'
      preLoaderRoute: typeof SupportRequestsRouteImport
      parentRoute: typeof SupportRoute
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/all': {
      id: '/vendor/all'
      path: '/all'
      fullPath: '/vendor/all'
      preLoaderRoute: typeof VendorAllRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/approved': {
      id: '/vendor/approved'
      path: '/approved'
      fullPath: '/vendor/approved'
      preLoaderRoute: typeof VendorApprovedRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/logs': {
      id: '/vendor/logs'
      path: '/logs'
      fullPath: '/vendor/logs'
      preLoaderRoute: typeof VendorLogsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/pending': {
      id: '/vendor/pending'
      path: '/pending'
      fullPath: '/vendor/pending'
      preLoaderRoute: typeof VendorPendingRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/rejected': {
      id: '/vendor/rejected'
      path: '/rejected'
      fullPath: '/vendor/rejected'
      preLoaderRoute: typeof VendorRejectedRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/team': {
      id: '/vendor/team'
      path: '/team'
      fullPath: '/vendor/team'
      preLoaderRoute: typeof VendorTeamRouteImport
      parentRoute: typeof VendorRoute
    }
    '/verifier/': {
      id: '/verifier/'
      path: '/'
      fullPath: '/verifier/'
      preLoaderRoute: typeof VerifierIndexRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/blockers': {
      id: '/verifier/blockers'
      path: '/blockers'
      fullPath: '/verifier/blockers'
      preLoaderRoute: typeof VerifierBlockersRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/history': {
      id: '/verifier/history'
      path: '/history'
      fullPath: '/verifier/history'
      preLoaderRoute: typeof VerifierHistoryRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/performance': {
      id: '/verifier/performance'
      path: '/performance'
      fullPath: '/verifier/performance'
      preLoaderRoute: typeof VerifierPerformanceRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/queue': {
      id: '/verifier/queue'
      path: '/queue'
      fullPath: '/verifier/queue'
      preLoaderRoute: typeof VerifierQueueRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/sla': {
      id: '/verifier/sla'
      path: '/sla'
      fullPath: '/verifier/sla'
      preLoaderRoute: typeof VerifierSlaRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/reports/verify/$authenticityCode': {
      id: '/reports/verify/$authenticityCode'
      path: '/reports/verify/$authenticityCode'
      fullPath: '/reports/verify/$authenticityCode'
      preLoaderRoute: typeof ReportsVerifyAuthenticityCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminClientPortalRoute: typeof AdminClientPortalRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminExceptionsRoute: typeof AdminExceptionsRoute
  AdminFieldRoute: typeof AdminFieldRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminPrivacyRoute: typeof AdminPrivacyRoute
  AdminQaRoute: typeof AdminQaRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifierRoute: typeof AdminVerifierRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminClientPortalRoute: AdminClientPortalRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminExceptionsRoute: AdminExceptionsRoute,
  AdminFieldRoute: AdminFieldRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminPrivacyRoute: AdminPrivacyRoute,
  AdminQaRoute: AdminQaRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifierRoute: AdminVerifierRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientPortalRouteChildren {
  ClientPortalActionsRoute: typeof ClientPortalActionsRoute
  ClientPortalAnalyticsRoute: typeof ClientPortalAnalyticsRoute
  ClientPortalBillingRoute: typeof ClientPortalBillingRoute
  ClientPortalReportsRoute: typeof ClientPortalReportsRoute
  ClientPortalVerificationsRoute: typeof ClientPortalVerificationsRoute
  ClientPortalIndexRoute: typeof ClientPortalIndexRoute
}

const ClientPortalRouteChildren: ClientPortalRouteChildren = {
  ClientPortalActionsRoute: ClientPortalActionsRoute,
  ClientPortalAnalyticsRoute: ClientPortalAnalyticsRoute,
  ClientPortalBillingRoute: ClientPortalBillingRoute,
  ClientPortalReportsRoute: ClientPortalReportsRoute,
  ClientPortalVerificationsRoute: ClientPortalVerificationsRoute,
  ClientPortalIndexRoute: ClientPortalIndexRoute,
}

const ClientPortalRouteWithChildren = ClientPortalRoute._addFileChildren(
  ClientPortalRouteChildren,
)

interface OperationsRouteChildren {
  OperationsAssignmentsRoute: typeof OperationsAssignmentsRoute
  OperationsCasesRoute: typeof OperationsCasesRoute
  OperationsClarificationsRoute: typeof OperationsClarificationsRoute
  OperationsExceptionsRoute: typeof OperationsExceptionsRoute
  OperationsFieldRoute: typeof OperationsFieldRoute
  OperationsSlaRoute: typeof OperationsSlaRoute
  OperationsTeamRoute: typeof OperationsTeamRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsAssignmentsRoute: OperationsAssignmentsRoute,
  OperationsCasesRoute: OperationsCasesRoute,
  OperationsClarificationsRoute: OperationsClarificationsRoute,
  OperationsExceptionsRoute: OperationsExceptionsRoute,
  OperationsFieldRoute: OperationsFieldRoute,
  OperationsSlaRoute: OperationsSlaRoute,
  OperationsTeamRoute: OperationsTeamRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface SalesCrmRouteChildren {
  SalesCrmAccountsRoute: typeof SalesCrmAccountsRoute
  SalesCrmActivitiesRoute: typeof SalesCrmActivitiesRoute
  SalesCrmFollowUpsRoute: typeof SalesCrmFollowUpsRoute
  SalesCrmForecastRoute: typeof SalesCrmForecastRoute
  SalesCrmOpportunitiesRoute: typeof SalesCrmOpportunitiesRoute
  SalesCrmSettingsRoute: typeof SalesCrmSettingsRoute
  SalesCrmTeamRoute: typeof SalesCrmTeamRoute
  SalesCrmIndexRoute: typeof SalesCrmIndexRoute
}

const SalesCrmRouteChildren: SalesCrmRouteChildren = {
  SalesCrmAccountsRoute: SalesCrmAccountsRoute,
  SalesCrmActivitiesRoute: SalesCrmActivitiesRoute,
  SalesCrmFollowUpsRoute: SalesCrmFollowUpsRoute,
  SalesCrmForecastRoute: SalesCrmForecastRoute,
  SalesCrmOpportunitiesRoute: SalesCrmOpportunitiesRoute,
  SalesCrmSettingsRoute: SalesCrmSettingsRoute,
  SalesCrmTeamRoute: SalesCrmTeamRoute,
  SalesCrmIndexRoute: SalesCrmIndexRoute,
}

const SalesCrmRouteWithChildren = SalesCrmRoute._addFileChildren(
  SalesCrmRouteChildren,
)

interface SpocRmRouteChildren {
  SpocRmClientsRoute: typeof SpocRmClientsRoute
  SpocRmRecordsRoute: typeof SpocRmRecordsRoute
  SpocRmVendorsRoute: typeof SpocRmVendorsRoute
  SpocRmIndexRoute: typeof SpocRmIndexRoute
}

const SpocRmRouteChildren: SpocRmRouteChildren = {
  SpocRmClientsRoute: SpocRmClientsRoute,
  SpocRmRecordsRoute: SpocRmRecordsRoute,
  SpocRmVendorsRoute: SpocRmVendorsRoute,
  SpocRmIndexRoute: SpocRmIndexRoute,
}

const SpocRmRouteWithChildren =
  SpocRmRoute._addFileChildren(SpocRmRouteChildren)

interface SupportRouteChildren {
  SupportEmployeesRoute: typeof SupportEmployeesRoute
  SupportRequestsRoute: typeof SupportRequestsRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportEmployeesRoute: SupportEmployeesRoute,
  SupportRequestsRoute: SupportRequestsRoute,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface VendorRouteChildren {
  VendorAllRoute: typeof VendorAllRoute
  VendorApprovedRoute: typeof VendorApprovedRoute
  VendorLogsRoute: typeof VendorLogsRoute
  VendorPendingRoute: typeof VendorPendingRoute
  VendorRejectedRoute: typeof VendorRejectedRoute
  VendorTeamRoute: typeof VendorTeamRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAllRoute: VendorAllRoute,
  VendorApprovedRoute: VendorApprovedRoute,
  VendorLogsRoute: VendorLogsRoute,
  VendorPendingRoute: VendorPendingRoute,
  VendorRejectedRoute: VendorRejectedRoute,
  VendorTeamRoute: VendorTeamRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

interface VerifierRouteChildren {
  VerifierBlockersRoute: typeof VerifierBlockersRoute
  VerifierHistoryRoute: typeof VerifierHistoryRoute
  VerifierPerformanceRoute: typeof VerifierPerformanceRoute
  VerifierQueueRoute: typeof VerifierQueueRoute
  VerifierSlaRoute: typeof VerifierSlaRoute
  VerifierIndexRoute: typeof VerifierIndexRoute
}

const VerifierRouteChildren: VerifierRouteChildren = {
  VerifierBlockersRoute: VerifierBlockersRoute,
  VerifierHistoryRoute: VerifierHistoryRoute,
  VerifierPerformanceRoute: VerifierPerformanceRoute,
  VerifierQueueRoute: VerifierQueueRoute,
  VerifierSlaRoute: VerifierSlaRoute,
  VerifierIndexRoute: VerifierIndexRoute,
}

const VerifierRouteWithChildren = VerifierRoute._addFileChildren(
  VerifierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ClientPortalRoute: ClientPortalRouteWithChildren,
  FieldExecutiveRoute: FieldExecutiveRoute,
  FinanceRoute: FinanceRoute,
  OperationsRoute: OperationsRouteWithChildren,
  QaReviewRoute: QaReviewRoute,
  SalesCrmRoute: SalesCrmRouteWithChildren,
  SpocRmRoute: SpocRmRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  VerifierRoute: VerifierRouteWithChildren,
  CandidateAccessIdRoute: CandidateAccessIdRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ClarificationClarificationIdRoute: ClarificationClarificationIdRoute,
  ConsentConsentIdRoute: ConsentConsentIdRoute,
  FinanceBillingRoute: FinanceBillingRoute,
  FinanceCollectionsRoute: FinanceCollectionsRoute,
  FinanceCreditRoute: FinanceCreditRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinanceStatementsRoute: FinanceStatementsRoute,
  QaReviewCorrectionsRoute: QaReviewCorrectionsRoute,
  QaReviewHistoryRoute: QaReviewHistoryRoute,
  QaReviewMineRoute: QaReviewMineRoute,
  QaReviewOverviewRoute: QaReviewOverviewRoute,
  ReportsVerifyAuthenticityCodeRoute: ReportsVerifyAuthenticityCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
